package com.sample.rules

declare Pytanie
    tresc : String
    odpowiedz : String
end

rule "What kind of book do you want to read?"
    when
    then
        Pytanie pytanie = new Pytanie();
        pytanie.setTresc("Do you want some good popular fiction?");
        insert(pytanie);
end

rule "Popular fiction response - Yes"
    when
        $p : Pytanie(tresc == "Do you want some good popular fiction?", odpowiedz == "yes")
    then
        Pytanie nowePytanie = new Pytanie();
        nowePytanie.setTresc("Thrillers?");
        insert(nowePytanie);
end

rule "Popular fiction response - No"
    when
        $p : Pytanie(tresc == "Do you want some good popular fiction?", odpowiedz == "no")
    then
        Pytanie nowePytanie = new Pytanie();
        nowePytanie.setTresc("How about literary fiction?");
        insert(nowePytanie);
end


